# Generated by Django 6.0 on 2026-01-02 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_created_at_appointment_reason_and_more'),
        ('billing', '0002_invoice_delete_bill'),
        ('patients', '0002_remove_patient_age_remove_patient_gender_and_more'),
        ('wards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='item_list',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='paid_at',
        ),
        migrations.AddField(
            model_name='invoice',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='wards.admission'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='appointments.appointment'),
        ),
    ]
