# Generated by Django 6.0 on 2026-01-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('patient', 'Patient'), ('pharmacist', 'Pharmacist'), ('lab_tech', 'Lab Technician'), ('cashier', 'Cashier')], default='admin', max_length=10),
        ),
    ]
