# Generated by Django 6.0 on 2026-01-02 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_created_at_appointment_reason_and_more'),
        ('nurses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitalsigns',
            name='nurse',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='phone',
        ),
        migrations.AddField(
            model_name='nurse',
            name='department',
            field=models.CharField(default='OPD', help_text='e.g. Pediatrics, ICU', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nurse',
            name='qualifications',
            field=models.CharField(help_text='e.g. BSN, RN, CNA', max_length=100),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=1, help_text='°C', max_digits=4)),
                ('pulse_rate', models.IntegerField(help_text='BPM')),
                ('respiration_rate', models.IntegerField(default=16, help_text='Breaths/min')),
                ('blood_pressure', models.CharField(help_text='e.g. 120/80', max_length=20)),
                ('oxygen_saturation', models.IntegerField(default=98, help_text='SpO2 %')),
                ('weight', models.DecimalField(decimal_places=2, help_text='kg', max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, default=0.0, help_text='meters', max_digits=5)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='appointments.appointment')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nurses.nurse')),
            ],
        ),
        migrations.DeleteModel(
            name='NurseAssignment',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
        migrations.DeleteModel(
            name='VitalSigns',
        ),
    ]
