# Generated by Django 6.0 on 2026-01-02 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_doctor_available_days_doctor_department_and_more'),
        ('patients', '0002_remove_patient_age_remove_patient_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(help_text="e.g. 'A-101'", max_length=10)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Maintenance', 'Maintenance')], default='Available', max_length=20)),
                ('price_per_night', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Surgical Ward A'", max_length=50)),
                ('ward_type', models.CharField(choices=[('General', 'General Ward'), ('Private', 'Private Room'), ('ICU', 'Intensive Care Unit'), ('Maternity', 'Maternity Ward'), ('Pediatric', 'Pediatric Ward')], max_length=20)),
                ('capacity', models.IntegerField(default=10)),
                ('floor', models.CharField(help_text="e.g. '2nd Floor'", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(help_text='Reason for admission')),
                ('is_discharged', models.BooleanField(default=False)),
                ('admitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wards.bed')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='wards.ward'),
        ),
    ]
