# Generated by Django 6.0 on 2026-01-01 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_appointment_created_at_appointment_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(help_text='What is the patient complaining about?')),
                ('diagnosis', models.TextField(help_text="Doctor's findings")),
                ('medication', models.TextField(help_text='List of medicines (e.g., Paracetamol 500mg - 2x daily)')),
                ('notes', models.TextField(blank=True, help_text='Extra advice (e.g., Drink water, Rest)')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment')),
            ],
        ),
    ]
