# Generated by Django 6.0 on 2026-01-02 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_created_at_appointment_reason_and_more'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='issued_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(default='yeah'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_dispensed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medication',
            field=models.TextField(help_text="Doctor's notes on meds"),
        ),
    ]
